# Generated by Django 5.0.1 on 2026-04-28 08:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantemailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='e.g., "starter", "professional", "enterprise"', unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, help_text='Monthly subscription price (UGX)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_annual', models.DecimalField(decimal_places=2, help_text='Annual subscription price (UGX). Can be less than 12x monthly.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_users', models.PositiveIntegerField(help_text='Max concurrent user seats')),
                ('max_outlets', models.PositiveIntegerField(help_text='Max physical outlets/branches')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of enabled feature slugs: ["pos", "inventory", "fuel", "hr", "accounting", "project_management", "asset_management"]')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive plans cannot be selected at registration')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sort order on pricing page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=10)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_days', models.PositiveIntegerField(default=14, help_text='Default trial period in days')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended (payment overdue)'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due')], default='trial', max_length=20)),
                ('current_period_start', models.DateTimeField(help_text='Billing period start (current or upcoming)')),
                ('current_period_end', models.DateTimeField(help_text='Billing period end; next invoice due then')),
                ('next_billing_date', models.DateTimeField(help_text='When next payment attempt should occur')),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.CharField(blank=True, help_text='e.g., "Invoice overdue 30+ days"', max_length=255)),
                ('failed_payment_count', models.PositiveIntegerField(default=0)),
                ('last_payment_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.subscriptionplan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Auto-generated: e.g., INV-2026-00001', max_length=50, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(help_text='Payment due date (e.g., 14 days after issued)')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('line_items', models.JSONField(blank=True, default=list, help_text='[{"description": "Plan fee", "quantity": 1, "unit_price": 500000, "total": 500000}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.tenantsubscription')),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tenantsubscription',
            index=models.Index(fields=['status', 'next_billing_date'], name='tenants_ten_status_2ac43f_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantsubscription',
            index=models.Index(fields=['tenant', 'status'], name='tenants_ten_tenant__679851_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['subscription', 'status'], name='tenants_sub_subscri_101548_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['due_date', 'status'], name='tenants_sub_due_dat_ebb235_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptioninvoice',
            unique_together={('subscription', 'period_start', 'period_end')},
        ),
    ]
