# Generated by Django 5.0.1 on 2026-04-28 14:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "Fuel Pumps", "Office Furniture"', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_useful_life_years', models.PositiveIntegerField(default=5, help_text='Default depreciation period')),
                ('default_depreciation_method', models.CharField(choices=[('straight_line', 'Straight-Line'), ('reducing_balance', 'Reducing Balance (Declining Balance)'), ('units', 'Units of Production'), ('none', 'No Depreciation')], default='straight_line', max_length=20)),
                ('default_depreciation_rate_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Annual depreciation rate (%) for reducing balance method', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('gl_account', models.CharField(blank=True, help_text='General Ledger account code for assets (e.g., "1200")', max_length=50)),
                ('accumulated_depreciation_account', models.CharField(blank=True, help_text='GL account for accumulated depreciation contra-asset', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(help_text='Unique asset identifier (e.g., "PUMP-001", "TANK-A1")', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Asset description (e.g., "Fuel Pump - Premium Island 1")', max_length=255)),
                ('acquisition_date', models.DateField(help_text='Date asset was purchased/capitalized')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Original/cost basis', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('useful_life_years', models.PositiveIntegerField(help_text='Depreciation period in years')),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight-Line'), ('reducing_balance', 'Reducing Balance (Declining Balance)'), ('units', 'Units of Production'), ('none', 'No Depreciation')], default='straight_line', max_length=20)),
                ('depreciation_rate_pct', models.DecimalField(blank=True, decimal_places=2, help_text='For reducing balance method', max_digits=5, null=True)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total depreciation to date (updated monthly)', max_digits=15)),
                ('location', models.CharField(blank=True, help_text='Physical location (e.g., "Main Outlet, Island 1")', max_length=255)),
                ('assigned_to_id', models.IntegerField(blank=True, help_text='Employee ID responsible for asset (cross-schema safe)', null=True)),
                ('status', models.CharField(choices=[('active', 'In Service'), ('idle', 'Idle/Not In Use'), ('maintenance', 'Under Maintenance'), ('disposed', 'Disposed')], default='active', max_length=20)),
                ('residual_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Estimated scrap/salvage value', max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True, help_text='Link to asset photo (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory')),
            ],
            options={
                'ordering': ['asset_code'],
            },
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField()),
                ('disposal_method', models.CharField(choices=[('sale', 'Sold'), ('scrap', 'Scrapped'), ('donation', 'Donated'), ('write_off', 'Written Off'), ('other', 'Other')], max_length=20)),
                ('proceeds', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cash or value received (0 if scrapped)', max_digits=15)),
                ('book_value_at_disposal', models.DecimalField(decimal_places=2, help_text='Net book value on disposal date (auto-calculated)', max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('journal_entry_id', models.IntegerField(blank=True, help_text='JournalEntry ID if auto-journalized (optional finance integration)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disposal', to='assets.asset')),
            ],
            options={
                'ordering': ['-disposal_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive Maintenance'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('calibration', 'Calibration'), ('other', 'Other')], max_length=20)),
                ('performed_date', models.DateField()),
                ('description', models.TextField(help_text='What was done, what was replaced, etc.')),
                ('performed_by', models.CharField(blank=True, help_text='Technician name or vendor', max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Maintenance cost (expense, not capitalized)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('downtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Hours asset was unavailable', max_digits=8)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='assets.asset')),
            ],
            options={
                'ordering': ['-performed_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to_id', models.IntegerField(help_text='Employee ID or department ID (cross-schema safe)')),
                ('assigned_to_type', models.CharField(choices=[('employee', 'Employee'), ('department', 'Department')], default='employee', max_length=20)),
                ('assigned_date', models.DateField(help_text='When assignment began')),
                ('returned_date', models.DateField(blank=True, help_text='When asset was returned (null if currently assigned)', null=True)),
                ('is_current', models.BooleanField(default=True, help_text='True if this is the active assignment')),
                ('notes', models.TextField(blank=True, help_text='Condition notes at assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset')),
            ],
            options={
                'ordering': ['-assigned_date'],
                'indexes': [models.Index(fields=['asset', 'is_current'], name='assets_asse_asset_i_de8dea_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category', 'status'], name='assets_asse_categor_c15078_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_asse_status_347ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancelog',
            index=models.Index(fields=['asset', 'performed_date'], name='assets_main_asset_i_e603b6_idx'),
        ),
    ]
