# Generated by Django 5.0.1 on 2026-04-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.IntegerField(db_index=True)),
                ('notification_type', models.CharField(choices=[('low_fuel', 'Low Fuel'), ('low_stock', 'Low Stock'), ('variance_alert', 'Variance Alert'), ('shift_reminder', 'Shift Reminder'), ('payment_failure', 'Payment Failure'), ('approval_required', 'Approval Required'), ('system', 'System')], max_length=20)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS')], default='in_app', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('source_type', models.CharField(blank=True, help_text='Model name that triggered this notification (e.g. FuelReconciliation)', max_length=50)),
                ('reference_id', models.IntegerField(blank=True, help_text='PK of the source object', null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_id', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient_id', 'read_at'], name='notificatio_recipie_564b1f_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('notification_type', models.CharField(choices=[('low_fuel', 'Low Fuel'), ('low_stock', 'Low Stock'), ('variance_alert', 'Variance Alert'), ('shift_reminder', 'Shift Reminder'), ('payment_failure', 'Payment Failure'), ('approval_required', 'Approval Required'), ('system', 'System')], max_length=20)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS')], default='in_app', max_length=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['notification_type', 'channel'],
                'unique_together': {('user_id', 'notification_type', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('low_fuel', 'Low Fuel'), ('low_stock', 'Low Stock'), ('variance_alert', 'Variance Alert'), ('shift_reminder', 'Shift Reminder'), ('payment_failure', 'Payment Failure'), ('approval_required', 'Approval Required'), ('system', 'System')], max_length=20)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(help_text='Template body. Use {variable_name} placeholders.')),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of variable names available in this template.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['notification_type', 'channel'],
                'unique_together': {('notification_type', 'channel')},
            },
        ),
    ]
