"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from decouple import config
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure--f_=-(hb8eky^ldxh4u$o$f8o&7#()^y8&5kw^y8wc+*#*hsn2')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['*']


# Application definition

SHARED_APPS = [
    'django_tenants',  # mandatory
    'tenants',         # our app for managing tenants
    'corsheaders',     # For Cross-Origin Resource Sharing
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    'django_filters',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.apple',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'drf_spectacular',
    'api',
    'users',
]

TENANT_APPS = [
    # Apps that are tenant-specific
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'outlets',
    'products',
    'sales',
    'inventory',
    'reports',
    'finance',
    'hr',
    'fuel',
    'notifications',
    'system_config',
    'fiscalization',
    'payments',
]

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware', # mandatory, keep at the top
    "corsheaders.middleware.CorsMiddleware",                # Should be as high as possible
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Change in production
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://your-frontend-domain.com",
]

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

TENANT_MODEL = 'tenants.Client'
TENANT_DOMAIN_MODEL = 'tenants.Domain'
SHOW_PUBLIC_IF_NO_TENANT_FOUND = True

# Base domain used when constructing tenant URLs during self-service registration.
# In local dev: 'localhost' → tenants live at '<schema>.localhost'.
# In production: set via env var, e.g. 'nexuserp.com' → '<schema>.nexuserp.com'.
TENANT_BASE_DOMAIN = config('TENANT_BASE_DOMAIN', default='localhost')

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend', # mandatory
        'NAME': config('DB_NAME', default='nexus_db'),
        'USER': config('DB_USER', default='nexus_user'),
        'PASSWORD': config('DB_PASSWORD', default='nexus_pass'),
        'HOST': config('DB_HOST', default='db'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-ug'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Public webhook endpoint — generous enough for legit retries,
        # tight enough to discourage spam/bruteforce of payment references.
        'payment-callback': '120/min',
        # Tenant signup — heavily rate-limited because each successful
        # call provisions a Postgres schema (expensive + irreversible).
        'tenant-registration': '3/hour',
    },
}

# Self-service tenant registration. While disabled (default), the public
# /api/tenants/register/ endpoint returns 503. Flip to True only after the
# email-verification + async-provisioning workflow ships.
TENANT_SELF_REGISTRATION_ENABLED = config(
    'TENANT_SELF_REGISTRATION_ENABLED', default=False, cast=bool,
)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Nexus ERP API',
    'DESCRIPTION': 'Multi-tenant Fuel Station ERP — API Documentation',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'Auth', 'description': 'Authentication & social login'},
        {'name': 'Users', 'description': 'User management'},
        {'name': 'Outlets', 'description': 'Outlet management'},
        {'name': 'Categories', 'description': 'Product categories'},
        {'name': 'Products', 'description': 'Product catalog & stock'},
        {'name': 'Shifts', 'description': 'Cashier shift management'},
        {'name': 'Checkout', 'description': 'POS checkout'},
        {'name': 'Sales', 'description': 'Sale history & receipts'},
        {'name': 'Discounts', 'description': 'Discount management'},
        {'name': 'Suppliers', 'description': 'Supplier management'},
        {'name': 'Outlet Stock', 'description': 'Per-outlet stock levels'},
        {'name': 'Purchase Orders', 'description': 'Procurement workflow'},
        {'name': 'Stock Transfers', 'description': 'Inter-outlet stock transfers'},
        {'name': 'Stock Audit Log', 'description': 'Immutable stock movement history'},
        {'name': 'Reports', 'description': 'Sales, inventory & shift reports'},
        {'name': 'Accounts', 'description': 'Chart of accounts'},
        {'name': 'Fiscal Periods', 'description': 'Accounting periods'},
        {'name': 'Journal Entries', 'description': 'Double-entry journal entries'},
        {'name': 'Financial Reports', 'description': 'Trial balance, P&L, balance sheet'},
        {'name': 'Departments', 'description': 'Department management'},
        {'name': 'Employees', 'description': 'Employee records'},
        {'name': 'Leave', 'description': 'Leave types, requests, and balances'},
        {'name': 'Attendance', 'description': 'Clock in/out and attendance records'},
        {'name': 'Payroll', 'description': 'Payroll periods and pay slips'},
        {'name': 'Fuel Pumps', 'description': 'Pump management'},
        {'name': 'Fuel Tanks', 'description': 'Tank levels and readings'},
        {'name': 'Fuel Deliveries', 'description': 'Fuel delivery tracking'},
        {'name': 'Fuel Reconciliation', 'description': 'Daily fuel reconciliation'},
        {'name': 'Fuel Reports', 'description': 'Pump, variance, and tank reports'},
    ],
}

# Cache
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{config("REDIS_HOST", default="redis")}:{config("REDIS_PORT", default="6379")}/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# django-allauth
SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': config('GOOGLE_CLIENT_ID', default=''),
            'secret': config('GOOGLE_CLIENT_SECRET', default=''),
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'apple': {
        'APP': {
            'client_id': config('APPLE_CLIENT_ID', default=''),
            'secret': config('APPLE_CLIENT_SECRET', default=''),
            'key': config('APPLE_KEY_ID', default=''),
            'certificate_key': config('APPLE_CERTIFICATE_KEY', default=''),
        },
    },
}

# dj-rest-auth
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_HTTPONLY': False,
}

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'

# Email
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Nexus ERP <noreply@nexuserp.com>')

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': config('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': config('DB_LOG_LEVEL', default='WARNING'),
            'propagate': False,
        },
        'sales': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}
