# Generated by Django 5.0.1 on 2026-04-28 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "PO Approval — High Value"', max_length=200)),
                ('resource_type', models.CharField(choices=[('purchase_order', 'Purchase Order'), ('leave_request', 'Leave Request'), ('payroll_run', 'Payroll Run'), ('cash_requisition', 'Cash Requisition'), ('stock_adjustment', 'Stock Adjustment')], max_length=50)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum transaction amount to trigger approval', max_digits=15, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for unlimited upper bound', max_digits=15, null=True)),
                ('approval_levels', models.JSONField(help_text='List of approval levels: [{level, role, min_approvers, description}]')),
                ('auto_approve_if_under', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-approve if amount <= this threshold', max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['resource_type', 'min_amount'],
                'indexes': [models.Index(fields=['resource_type', 'is_active'], name='approvals_a_resourc_bdf98b_idx'), models.Index(fields=['is_active'], name='approvals_a_is_acti_deb994_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('purchase_order', 'Purchase Order'), ('leave_request', 'Leave Request'), ('payroll_run', 'Payroll Run'), ('cash_requisition', 'Cash Requisition'), ('stock_adjustment', 'Stock Adjustment')], max_length=50)),
                ('resource_id', models.IntegerField(help_text='FK to PurchaseOrder, LeaveRequest, PayrollPeriod, etc. (cross-schema safe)')),
                ('requested_by_id', models.IntegerField(help_text='User who created the transaction (cross-schema safe)')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Transaction amount for audit', max_digits=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting Approval'), ('approved', 'Fully Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled (transaction cancelled)'), ('auto_approved', 'Auto-Approved')], default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_chain_state', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, help_text='Initial notes from requestor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='approvals.approvalpolicy')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.IntegerField(help_text='User ID of approver (cross-schema safe)')),
                ('level', models.PositiveIntegerField(help_text='Approval level (1, 2, 3, etc.)')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approvalrequest')),
            ],
            options={
                'ordering': ['level', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'resolved_at'], name='approvals_a_status_4cd003_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['resource_type', 'resource_id'], name='approvals_a_resourc_b596b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalrequest',
            unique_together={('resource_type', 'resource_id')},
        ),
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['approval_request', 'level'], name='approvals_a_approva_542d7f_idx'),
        ),
    ]
