# Generated by Django 5.0.1 on 2026-05-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalpolicy',
            name='resource_type',
            field=models.CharField(choices=[('purchase_order', 'Purchase Order'), ('leave_request', 'Leave Request'), ('payroll_run', 'Payroll Run'), ('cash_requisition', 'Cash Requisition'), ('stock_adjustment', 'Stock Adjustment'), ('project', 'Project')], max_length=50),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='resource_type',
            field=models.CharField(choices=[('purchase_order', 'Purchase Order'), ('leave_request', 'Leave Request'), ('payroll_run', 'Payroll Run'), ('cash_requisition', 'Cash Requisition'), ('stock_adjustment', 'Stock Adjustment'), ('project', 'Project')], max_length=50),
        ),
    ]
