# Generated by Django 5.0.1 on 2026-05-02 16:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0002_add_project_resource_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(help_text='Auto-generated: PRJ-YYYYMMDD-XXXX', max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('manager_id', models.IntegerField(help_text='User ID of project manager')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, help_text='Approved project budget (UGX)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actual_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Running total of logged expenses', max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='approvals.approvalrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('labour', 'Labour'), ('materials', 'Materials'), ('equipment', 'Equipment Hire'), ('subcontract', 'Subcontract'), ('travel', 'Travel & Transport'), ('other', 'Other')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount (UGX)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expense_date', models.DateField()),
                ('incurred_by_id', models.IntegerField(help_text='User ID who incurred the expense')),
                ('approved_by_id', models.IntegerField(blank=True, help_text='User ID who approved the expense', null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('journal_entry_id', models.IntegerField(blank=True, help_text='JournalEntry ID if expense was journalised to GL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project')),
            ],
            options={
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assigned_to_id', models.IntegerField(blank=True, help_text='Employee ID assigned to this task', null=True)),
                ('created_by_id', models.IntegerField(help_text='User who created the task')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='todo', max_length=15)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['priority', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField(help_text='User ID of staff member')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, help_text='Hours worked (minimum 0.25 = 15 min)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.25'))])),
                ('description', models.TextField(blank=True, help_text='Summary of work done')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='projects.projecttask')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'manager_id'], name='projects_pr_status_b7ef66_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexpense',
            index=models.Index(fields=['project', 'expense_date'], name='projects_pr_project_3afe4b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexpense',
            index=models.Index(fields=['category'], name='projects_pr_categor_c2bfae_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['project', 'status'], name='projects_pr_project_4795b4_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['assigned_to_id', 'status'], name='projects_pr_assigne_6d78ef_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttimeentry',
            index=models.Index(fields=['project', 'date'], name='projects_pr_project_21343d_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttimeentry',
            index=models.Index(fields=['staff_id', 'date'], name='projects_pr_staff_i_947d81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projecttimeentry',
            unique_together={('project', 'staff_id', 'date', 'task')},
        ),
    ]
