# Generated by Django 5.0.1 on 2026-05-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('shift_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('outlet_id', models.IntegerField()),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-synced_at'],
                'indexes': [models.Index(fields=['shift_id', 'synced_at'], name='mobile_api__shift_i_29082b_idx')],
            },
        ),
    ]
