# Generated by Django 5.0.1 on 2026-04-22 10:53

import config.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfrisConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin', models.CharField(blank=True, help_text='Uganda Revenue Authority Tax Identification Number', max_length=20)),
                ('legal_name', models.CharField(blank=True, help_text='Name as registered with URA (may differ from business_name)', max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(choices=[('mock', 'Mock (development / testing)'), ('weaf', 'Weaf Company Uganda (production)'), ('direct', 'Direct URA (future)')], default='mock', max_length=10)),
                ('is_enabled', models.BooleanField(default=False, help_text='Master switch. When off, sales skip fiscalization entirely.')),
                ('weaf_api_key', models.CharField(blank=True, max_length=255)),
                ('weaf_base_url', models.URLField(blank=True, default='', validators=[config.validators.validate_provider_url])),
                ('default_currency', models.CharField(default='UGX', max_length=3)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='Default VAT rate in percent', max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EFRIS Configuration',
                'verbose_name_plural': 'EFRIS Configuration',
            },
        ),
        migrations.CreateModel(
            name='FiscalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending submission'), ('submitted', 'Submitted, awaiting response'), ('accepted', 'Accepted by EFRIS'), ('rejected', 'Rejected by EFRIS'), ('failed', 'Submission failed (retryable)'), ('skipped', 'Skipped (fiscalization disabled)')], db_index=True, default='pending', max_length=12)),
                ('provider', models.CharField(max_length=10)),
                ('fdn', models.CharField(blank=True, db_index=True, help_text='Fiscal Document Number assigned by URA', max_length=64)),
                ('invoice_id', models.CharField(blank=True, help_text="Provider's invoice reference", max_length=64)),
                ('verification_code', models.CharField(blank=True, help_text='Anti-fake code to print on the receipt', max_length=64)),
                ('qr_code', models.TextField(blank=True, help_text='QR code data (URL or base64) to print on the receipt')),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_invoice', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='fiscalizati_status_4ac76a_idx')],
            },
        ),
    ]
