# Generated by Django 5.0.1 on 2026-05-02 14:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlets', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "Standard Bread Loaf BOM v2"', max_length=255)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('output_quantity', models.DecimalField(decimal_places=3, help_text='Units of finished product produced per BOM batch', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('output_unit', models.CharField(help_text='Unit of finished product (e.g., loaves, kg, litres)', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cost per unit of finished product (total BOM cost / output_quantity)', max_digits=15)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive BOMs cannot be used to create production orders')),
                ('notes', models.TextField(blank=True)),
                ('created_by_id', models.IntegerField(help_text='User ID who created this BOM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_product', models.OneToOneField(help_text='The product this BOM produces', on_delete=django.db.models.deletion.PROTECT, related_name='bill_of_materials', to='products.product')),
            ],
            options={
                'ordering': ['finished_product__name'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=3, help_text='Quantity of raw material needed per BOM batch (before waste)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(help_text='Unit of measurement (must match product stock unit)', max_length=20)),
                ('waste_factor_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentage of additional material to account for waste/shrinkage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manufacturing.billofmaterials')),
                ('raw_material', models.ForeignKey(help_text='Raw material product consumed in production', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Auto-generated: MFG-YYYYMMDD-XXXX', max_length=30, unique=True)),
                ('quantity_to_produce', models.DecimalField(decimal_places=3, help_text='Number of finished product units to produce', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('quantity_produced', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Actual units produced (set at completion)', max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ordered_by_id', models.IntegerField(help_text='User ID who created the order')),
                ('total_material_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sum of raw material costs at time of production', max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='manufacturing.billofmaterials')),
                ('outlet', models.ForeignKey(help_text='Outlet whose stock is adjusted on completion', on_delete=django.db.models.deletion.PROTECT, to='outlets.outlet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_planned', models.DecimalField(decimal_places=3, help_text='Quantity from BOM calculation', max_digits=12)),
                ('quantity_actual', models.DecimalField(decimal_places=3, help_text='Actual quantity consumed (may differ due to waste)', max_digits=12)),
                ('unit', models.CharField(max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit at time of production', max_digits=15)),
                ('line_cost', models.DecimalField(decimal_places=2, help_text='quantity_actual × unit_cost', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumed_materials', to='manufacturing.productionorder')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkInProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('materials_consumed_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Estimated value of materials used so far', max_digits=15)),
                ('percentage_complete', models.DecimalField(decimal_places=2, help_text='Estimated completion percentage (0–100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('notes', models.TextField(blank=True)),
                ('recorded_by_id', models.IntegerField(help_text='User ID who recorded this snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wip_snapshots', to='manufacturing.productionorder')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.AddIndex(
            model_name='billofmaterials',
            index=models.Index(fields=['is_active'], name='manufacturi_is_acti_f193aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bomitem',
            unique_together={('bom', 'raw_material')},
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status', 'outlet'], name='manufacturi_status_f59a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['bom'], name='manufacturi_bom_id_3e6844_idx'),
        ),
        migrations.AddIndex(
            model_name='workinprogress',
            index=models.Index(fields=['production_order', 'snapshot_date'], name='manufacturi_product_76552b_idx'),
        ),
    ]
