# Generated by Django 5.0.1 on 2026-04-28 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_number', models.CharField(help_text='Auto-generated: REQ-YYYY-##### ', max_length=50, unique=True)),
                ('requisition_type', models.CharField(choices=[('petty_cash', 'Petty Cash'), ('employee_advance', 'Employee Advance'), ('operational', 'Operational Expense')], max_length=30)),
                ('requested_by_id', models.IntegerField(help_text='Employee ID requesting cash')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('purpose', models.TextField(help_text='Why cash is needed')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('settled', 'Settled (employee returned balance)')], default='pending', max_length=20)),
                ('approved_by_id', models.IntegerField(blank=True, help_text='Final approver (manager or accountant)', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_by_id', models.IntegerField(blank=True, help_text='Cashier who paid out', null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('settled_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount returned (if not fully expended)', max_digits=15, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_requisitions', to='approvals.approvalrequest')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'requested_by_id'], name='finance_cas_status_7e8d4d_idx')],
            },
        ),
    ]
