# Generated by Django 5.0.1 on 2026-04-28 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='approval_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='approvals.approvalrequest'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('submitted', 'Submitted'), ('partial', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
