# Generated by Django 5.0.1 on 2026-05-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='Client-generated UUID for mobile offline deduplication. Null for web POS sales.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='source',
            field=models.CharField(choices=[('pos', 'Web POS'), ('mobile', 'Mobile App')], default='pos', max_length=10),
        ),
    ]
