# Generated by Django 5.0.1 on 2026-04-08 08:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Master switch. When off, all payment initiations are rejected.')),
                ('default_provider', models.CharField(choices=[('mock', 'Mock (development / testing)'), ('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money'), ('pesapal', 'Pesapal (cards + aggregated mobile money)')], default='mock', help_text='Provider used when caller does not specify one explicitly.', max_length=16)),
                ('default_currency', models.CharField(default='UGX', max_length=3)),
                ('mtn_enabled', models.BooleanField(default=False)),
                ('mtn_subscription_key', models.CharField(blank=True, max_length=255)),
                ('mtn_api_user', models.CharField(blank=True, max_length=255)),
                ('mtn_api_key', models.CharField(blank=True, max_length=255)),
                ('mtn_base_url', models.URLField(blank=True, default='https://sandbox.momodeveloper.mtn.com')),
                ('mtn_target_environment', models.CharField(blank=True, default='sandbox', help_text='"sandbox" for testing, "mtnuganda" for production.', max_length=32)),
                ('mtn_callback_url', models.URLField(blank=True)),
                ('airtel_enabled', models.BooleanField(default=False)),
                ('airtel_client_id', models.CharField(blank=True, max_length=255)),
                ('airtel_client_secret', models.CharField(blank=True, max_length=255)),
                ('airtel_base_url', models.URLField(blank=True, default='https://openapiuat.airtel.africa')),
                ('airtel_country', models.CharField(blank=True, default='UG', max_length=8)),
                ('airtel_currency', models.CharField(blank=True, default='UGX', max_length=3)),
                ('airtel_callback_url', models.URLField(blank=True)),
                ('pesapal_enabled', models.BooleanField(default=False)),
                ('pesapal_consumer_key', models.CharField(blank=True, max_length=255)),
                ('pesapal_consumer_secret', models.CharField(blank=True, max_length=255)),
                ('pesapal_base_url', models.URLField(blank=True, default='https://cybqa.pesapal.com/pesapalv3')),
                ('pesapal_ipn_id', models.CharField(blank=True, help_text='Registered IPN (Instant Payment Notification) ID from Pesapal.', max_length=128)),
                ('pesapal_callback_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Configuration',
                'verbose_name_plural': 'Payment Configuration',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mock', 'Mock (development / testing)'), ('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money'), ('pesapal', 'Pesapal (cards + aggregated mobile money)')], max_length=16)),
                ('method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('card', 'Card'), ('bank', 'Bank')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending — not yet sent to provider'), ('processing', 'Processing — awaiting customer / provider'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled by customer'), ('expired', 'Expired (timed out)')], db_index=True, default='pending', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('phone_number', models.CharField(blank=True, help_text='MSISDN in international format, e.g. 256772123456 (mobile money only).', max_length=20)),
                ('customer_email', models.CharField(blank=True, max_length=255)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('provider_transaction_id', models.CharField(blank=True, db_index=True, help_text="Provider's tracking id (MTN financialTransactionId, Pesapal orderTrackingId, etc.).", max_length=128)),
                ('provider_status_code', models.CharField(blank=True, max_length=64)),
                ('provider_status_message', models.TextField(blank=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('callback_payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('initiated_by', models.IntegerField(blank=True, help_text='users.User id of the cashier who initiated this payment.', null=True)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payments_pa_status_c4e513_idx'), models.Index(fields=['provider', 'status'], name='payments_pa_provide_c3bda6_idx')],
            },
        ),
    ]
