# Generated by Django 5.0.1 on 2026-04-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfig',
            name='airtel_disbursement_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='airtel_disbursement_client_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='airtel_disbursement_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='mtn_disbursement_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='mtn_disbursement_api_user',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='mtn_disbursement_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='mtn_disbursement_subscription_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('collection', 'Collection (customer pays us)'), ('disbursement', 'Disbursement (we pay customer/staff/supplier)')], db_index=True, default='collection', max_length=16),
        ),
    ]
