# Generated by Django 5.0.1 on 2026-04-28 08:51

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentconfig_airtel_disbursement_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentconfig',
            name='airtel_base_url',
            field=models.URLField(blank=True, default='https://openapiuat.airtel.africa', validators=[config.validators.validate_provider_url]),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='mtn_base_url',
            field=models.URLField(blank=True, default='https://sandbox.momodeveloper.mtn.com', validators=[config.validators.validate_provider_url]),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='pesapal_base_url',
            field=models.URLField(blank=True, default='https://cybqa.pesapal.com/pesapalv3', validators=[config.validators.validate_provider_url]),
        ),
    ]
