# Generated by Django 5.0.1 on 2026-04-04 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('outlets', '0001_initial'),
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pumps', to='outlets.outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pumps', to='products.product')),
            ],
            options={
                'ordering': ['outlet', 'pump_number'],
                'unique_together': {('outlet', 'pump_number')},
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('current_level', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tanks', to='outlets.outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tanks', to='products.product')),
            ],
            options={
                'ordering': ['outlet', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PumpReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_reading', models.DecimalField(decimal_places=3, max_digits=12)),
                ('closing_reading', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('recorded_by', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='fuel.pump')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pump_readings', to='sales.shift')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pump', 'created_at'], name='fuel_pumpre_pump_id_e30a4c_idx')],
                'unique_together': {('pump', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='FuelReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_stock', models.DecimalField(decimal_places=3, max_digits=12)),
                ('closing_stock', models.DecimalField(decimal_places=3, max_digits=12)),
                ('total_received', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_dispensed', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('expected_closing', models.DecimalField(decimal_places=3, max_digits=12)),
                ('variance', models.DecimalField(decimal_places=3, max_digits=12)),
                ('variance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('variance_type', models.CharField(choices=[('gain', 'Gain'), ('loss', 'Loss'), ('within_tolerance', 'Within Tolerance')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('reconciled_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_reconciliations', to='outlets.outlet')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='fuel.tank')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['outlet', 'date'], name='fuel_fuelre_outlet__1a48fc_idx'), models.Index(fields=['variance_type', 'date'], name='fuel_fuelre_varianc_d09792_idx')],
                'unique_together': {('date', 'tank')},
            },
        ),
        migrations.CreateModel(
            name='FuelDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField()),
                ('volume_ordered', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('volume_received', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_note_number', models.CharField(blank=True, max_length=100)),
                ('tank_level_before', models.DecimalField(decimal_places=3, max_digits=12)),
                ('tank_level_after', models.DecimalField(decimal_places=3, max_digits=12)),
                ('received_by', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_deliveries', to='inventory.supplier')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='fuel.tank')),
            ],
            options={
                'ordering': ['-delivery_date'],
                'indexes': [models.Index(fields=['tank', 'delivery_date'], name='fuel_fuelde_tank_id_0c07f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='TankReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_level', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reading_type', models.CharField(choices=[('manual', 'Manual Dip'), ('automatic', 'Automatic Gauge'), ('delivery', 'Post-Delivery'), ('reconciliation', 'Reconciliation')], max_length=15)),
                ('recorded_by', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('reading_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='fuel.tank')),
            ],
            options={
                'ordering': ['-reading_at'],
                'indexes': [models.Index(fields=['tank', 'reading_at'], name='fuel_tankre_tank_id_57d265_idx')],
            },
        ),
    ]
