# Generated by Django 5.0.1 on 2026-05-13 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('authorised', 'Authorised'), ('flowing', 'Flowing'), ('completed', 'Completed'), ('error', 'Error')], max_length=15)),
                ('litres', models.DecimalField(blank=True, decimal_places=3, help_text='Total litres dispensed. Only set on completed events.', max_digits=12, null=True)),
                ('amount_ugx', models.DecimalField(blank=True, decimal_places=0, help_text='Sale amount in UGX. Only set on completed events.', max_digits=12, null=True)),
                ('meter_start', models.DecimalField(blank=True, decimal_places=3, help_text='Pump odometer reading at start of dispense.', max_digits=12, null=True)),
                ('meter_end', models.DecimalField(blank=True, decimal_places=3, help_text='Pump odometer reading at end of dispense.', max_digits=12, null=True)),
                ('attendant_id', models.IntegerField(blank=True, help_text='User ID of the attendant on duty. Set by the app, not the hardware.', null=True)),
                ('source', models.CharField(choices=[('hardware', 'Hardware Controller'), ('mock', 'Mock Controller'), ('manual', 'Manual Entry')], default='hardware', max_length=10)),
                ('raw_payload', models.JSONField(default=dict, help_text='Raw payload as received from the controller, for debugging.')),
                ('occurred_at', models.DateTimeField(help_text='When the event occurred according to the hardware clock.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='fuel.pump')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['pump', 'occurred_at'], name='fuel_pumpev_pump_id_0d5793_idx'), models.Index(fields=['event_type', 'occurred_at'], name='fuel_pumpev_event_t_434c64_idx')],
            },
        ),
    ]
