# Generated by Django 5.0.1 on 2026-05-02 10:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price (UGX)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Computed from BOM ingredients. Update via update-bom action.', max_digits=15)),
                ('has_bom', models.BooleanField(default=False, help_text='True if ingredients must be deducted from stock on order')),
                ('is_available', models.BooleanField(default=True, help_text='Unavailable items cannot be ordered, even if in stock')),
                ('preparation_time_minutes', models.PositiveIntegerField(default=0, help_text='Estimated prep time; shown to kitchen staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cafe.menucategory')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_serving', models.DecimalField(decimal_places=3, help_text='How much of this product is used per serving', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Millilitres'), ('l', 'Litres'), ('pcs', 'Pieces'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cafe.menuitem')),
                ('product', models.ForeignKey(help_text='Inventory product used as ingredient', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'ordering': ['menu_item', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Auto-generated: ORD-YYYYMMDD-XXXX', max_length=30, unique=True)),
                ('order_type', models.CharField(choices=[('dine_in', 'Dine-In'), ('takeaway', 'Takeaway')], max_length=10)),
                ('table_number', models.CharField(blank=True, help_text='Table reference for dine-in orders', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending (received)'), ('preparing', 'Being Prepared'), ('ready', 'Ready for Collection / Service'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('cashier_id', models.IntegerField(help_text='User ID of cashier')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sum of order item line totals', max_digits=15)),
                ('notes', models.TextField(blank=True, help_text='Special instructions for kitchen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='cafe_menuor_status_94296c_idx'), models.Index(fields=['order_type'], name='cafe_menuor_order_t_3e9a92_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price at time of order (snapshot)', max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('special_instructions', models.TextField(blank=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafe.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cafe.menuorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(max_length=10)),
                ('reason', models.CharField(choices=[('expired', 'Expired'), ('spoiled', 'Spoiled'), ('overproduction', 'Overproduction'), ('spillage', 'Spillage/Breakage'), ('other', 'Other')], max_length=20)),
                ('cost_value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated loss value (quantity × cost price). Auto-computed if blank.', max_digits=15, null=True)),
                ('recorded_by_id', models.IntegerField(help_text='User ID who logged the waste')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Ingredient/product that was wasted', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'is_available'], name='cafe_menuit_categor_37ac0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemingredient',
            unique_together={('menu_item', 'product')},
        ),
        migrations.AddIndex(
            model_name='wastelog',
            index=models.Index(fields=['product', 'recorded_at'], name='cafe_wastel_product_f55731_idx'),
        ),
        migrations.AddIndex(
            model_name='wastelog',
            index=models.Index(fields=['reason'], name='cafe_wastel_reason_19d22d_idx'),
        ),
    ]
