# Generated by Django 5.0.1 on 2026-04-04 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('login', 'Login Events'), ('data_change', 'Data Changes'), ('deletion', 'Deletions'), ('permission_change', 'Permission Changes'), ('export', 'Data Exports')], max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('retention_days', models.PositiveIntegerField(default=90, help_text='Number of days to retain audit logs (7-3650)', validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(3650)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['log_type'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variance_tolerance_pct', models.DecimalField(decimal_places=2, default=0.5, help_text='Acceptable fuel variance percentage (0-10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('low_stock_threshold_pct', models.DecimalField(decimal_places=2, default=20.0, help_text='Low stock alert threshold as % of reorder level', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('low_fuel_threshold_pct', models.DecimalField(decimal_places=2, default=25.0, help_text='Low fuel alert threshold as % of tank capacity', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('currency_code', models.CharField(default='UGX', max_length=3)),
                ('timezone', models.CharField(default='Africa/Kampala', max_length=50)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('receipt_header', models.TextField(blank=True)),
                ('receipt_footer', models.TextField(blank=True)),
                ('enable_email_notifications', models.BooleanField(default=False)),
                ('enable_sms_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.CreateModel(
            name='ApprovalThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase_order', 'Purchase Order'), ('stock_transfer', 'Stock Transfer'), ('expense', 'Expense'), ('journal_entry', 'Journal Entry'), ('fuel_delivery', 'Fuel Delivery')], max_length=20)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for unlimited upper bound', max_digits=15, null=True)),
                ('requires_role', models.CharField(choices=[('manager', 'Manager'), ('admin', 'Admin')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['transaction_type', 'min_amount'],
                'indexes': [models.Index(fields=['transaction_type', 'is_active'], name='system_conf_transac_482201_idx')],
            },
        ),
    ]
