# Generated by Django 5.0.1 on 2026-05-02 16:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0002_alter_systemconfig_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='project_approval_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Budget threshold for project approval', max_digits=15),
        ),
    ]
